Comment out doormat on survey.html
canada-ca/design-system pull request #197
Opened 2023-03-08 15:28 UTC by LanaStewa

Comment out doormat

2023-03-31 20:17 UTC, LanaStewa commented on survey/survey.md
> +    </div>
```suggestion
 
```
To remove

2023-04-03 17:19 UTC, LanaStewa commented on survey/survey.md
> +title: Contact and support for the GC Task Success Survey
```suggestion
title: GC Task Success Survey
```

2023-04-03 17:20 UTC, LanaStewa commented on survey/survey.md
> +    <p>Measuring the user experience of Canada.ca.</p>
```suggestion
    <p>Measuring the visitor experience of Canada.ca.</p>
```

2023-04-03 17:23 UTC, LanaStewa commented on survey/survey.md
> +                    <p>Get survey datasets, access and download comments</p>
```suggestion
                    <p>Get survey datasets, access and download results</p>
```

2023-04-03 17:50 UTC, LanaStewa commented on survey/survey.md
> +    <p>Understanding results and user comments from your survey</p>
```suggestion
    <p>Understanding results and visitor comments from your survey</p>
```

2023-04-03 17:51 UTC, LanaStewa commented on survey/survey.md
> +                    <p>Get survey datasets, access and download results</p>
```suggestion
                    <p>Get survey datasets, access and download responses</p>
```

2023-04-03 17:56 UTC, LanaStewa commented on survey/about-tss.md
> +The survey helps center our work on user needs by:
```suggestion
The survey helps center our work on visitor needs by:
```

2023-04-03 17:57 UTC, LanaStewa commented on survey/about-tss.md
> +* measuring how effectively digital content is serving user needs
```suggestion
* measuring how effectively digital content is serving visitor needs
```

2023-04-03 17:57 UTC, LanaStewa commented on survey/about-tss.md
> +* receiving feedback from users about their experience
```suggestion
* receiving feedback from visitors about their experience
```

2023-04-03 17:57 UTC, LanaStewa commented on survey/about-tss.md
> +The GC Task Success Survey measures the performance of the Government of Canada web presence for users in three ways: task success, ease and satisfaction.
```suggestion
The GC Task Success Survey measures the performance of the Government of Canada web presence for visitors in three ways: task success, ease and satisfaction.
```

2023-04-03 17:59 UTC, LanaStewa commented on survey/about-tss.md
> +* receiving feedback from visitors about their experience
```suggestion
* receiving comments from visitors about their experience
```

2023-04-03 18:24 UTC, LanaStewa commented on survey/benefits.md
> +* [Improve content and navigation]()
```suggestion
* [Improve content and navigation](#improve-content-and-navigation)
```

2023-04-03 18:26 UTC, LanaStewa commented on survey/benefits.md
> +* [Decide what to improve]()
```suggestion
* [Decide what to improve](#decide-what-to-improve)
```

2023-04-03 18:27 UTC, LanaStewa commented on survey/benefits.md
> +* [Case studies]()
```suggestion
* [Case studies](#case-studies)
```

2023-04-03 18:30 UTC, LanaStewa commented on survey/benefits.md
> +            <p>Using feedback to improve the  Submit an EI report task</p>
```suggestion
            <p>Using comments to improve the  Submit an EI report task</p>
```

2023-04-03 18:33 UTC, LanaStewa commented on survey/case-study-ei.md
> +By reading GC Task Success Survey feedback for the Submit and Employment Insurance report task, the team at Employment and Social Development Canada (ESDC) was able to spot an issue that they believe
```suggestion
By reading GC Task Success Survey comments for the Submit and Employment Insurance report task, the team at Employment and Social Development Canada (ESDC) was able to spot an issue that they believed could be improved through minor content design changes.
```

2023-04-03 18:36 UTC, LanaStewa commented on survey/access-results.md
> +* [Quarterly survey results and comment analysis](#quarterly-survey-results-and-comment-analysis)
```suggestion

```

2023-04-03 18:38 UTC, LanaStewa commented on survey/access-results.md
> +[Get GC Task Success Survey results (internal only) ](https://www.gcpedia.gc.ca/wiki/Government_of_Canada_Task_Success_Survey_reports){: .btn .btn-primary}
```suggestion

```

2023-04-03 18:39 UTC, LanaStewa commented on survey/access-results.md
> +Download survey responses and open text comments as CSV or Excel files using the Feedback Viewer.
```suggestion
Download survey responses and comments as CSV or Excel files using the Feedback Viewer.
```

2023-04-03 18:40 UTC, LanaStewa commented on survey/access-results.md
> +Download annual results and reports from the GC Task Success Survey
```suggestion
Download annual and quarterly results from the GC Task Success Survey
```

2023-04-03 18:47 UTC, LanaStewa commented on survey/writing-tasks.md
> +Top tasks should reflect what users are coming to the site to do, rather than departmental priorities.
```suggestion
Top tasks should reflect what visitors are coming to the site to do, rather than departmental priorities.
```

2023-04-03 18:52 UTC, LanaStewa commented on survey/custom-list.md
> +* [Service standards](#standards)
```suggestion
* [When to consider a custom task list](#when-to-consider-a-custom-task-list)
* [How to request a custom task list](#how-to-request-a-custom-task-list])
* [Guidance for completing the custom task list template](#guidance-for-completing-the-custom-task-list template)
* [Service standards](#standards)
```

2023-04-03 18:52 UTC, LanaStewa commented on survey/custom-list.md
> +[See the user guide on GCPedia](https://www.gcpedia.gc.ca/wiki/Adobe_Analytics_User_Guide_-_Task_Success_Survey_Reports) (internal only)
```suggestion

```

2023-04-03 18:56 UTC, LanaStewa commented on survey/custom-list.md
> +* [Guidance for completing the custom task list template](#guidance-for-completing-the-custom-task-list template)
```suggestion
* [Guidance for completing the custom task list template](#guidance-for-completing-the-custom-task-list-template)
```

2023-04-03 18:56 UTC, LanaStewa commented on survey/custom-list.md
> +* [Service standards](#standards)
```suggestion
* [Service standards](#service-standards)
```

2023-04-03 19:01 UTC, LanaStewa commented on survey/custom-list.md
> +* [How to request a custom task list](#how-to-request-a-custom-task-list])
```suggestion
* [How to request a custom task list](#how-to-request-a-custom-task-list])
```

2023-04-03 19:02 UTC, LanaStewa commented on survey/custom-list.md
> +## How to request a custom task list
```suggestion
## How to request a custom task list
```

2023-04-03 19:03 UTC, LanaStewa commented on survey/custom-list.md
> +* [How to request a custom task list](#how-to-request-a-custom-task-list])
```suggestion
* [How to request a custom task list](#how-to-request-a-custom-task-list)
```

2023-04-03 19:05 UTC, LanaStewa commented on survey/support.md
> +* [When to contact the Digital Transformation Office](#digital-transformation-office)
```suggestion
* [When to contact Principal Publisher](#when-to-contact-principal-publisher)
* [When to contact the Digital Transformation Office](#when-to-contact-the-digital-transformation-office)
```

2023-04-03 19:16 UTC, LanaStewa commented on survey/support.md
> +* [Working group](#working-group)
```suggestion
* [When to contact Principal Publisher](#when-to-contact-Principal-Publisher)
* [When to contact the Digital Transformation Office](#when-to-contact-the-Digital-Transformation-Office)
```

2023-04-03 19:20 UTC, LanaStewa commented on survey/support.md
> +## Principal publisher
```suggestion
## When to contact Principal Publisher
```

2023-04-03 19:23 UTC, LanaStewa commented on survey/support.md
> +* taking action and implementing changes
```suggestion
* the Feedback Viewer tool
* writing tasks
* taking action and implementing changes
* joining the working group
```

2023-04-03 19:24 UTC, LanaStewa commented on survey/support.md
> +[Working group meeting agendas and presentations](https://www.gcpedia.gc.ca/wiki/Government_of_Canada_Task_Success_Survey/Working_Group) (internal only on GCPedia).
```suggestion
```

2023-04-03 19:28 UTC, LanaStewa commented on survey/support.md
> +## Digital Transformation Office
```suggestion
## When to contact the Digital Transformation Office
```

2023-04-04 14:31 UTC, LanaStewa commented on survey/support.md
> +
```suggestion
## When to contact the Digital Transformation Office

Contact the Digital Transformation Office for questions related to:

* the Feedback Viewer tool
* writing tasks
* taking action and implementing changes
LanaStewa marked this conversation as resolved.
* joining the working group

Email: [dto.btn@tbs-sct.gc.ca](mailto:dto.btn@tbs-sct.gc.ca)
```

2023-04-04 14:31 UTC, LanaStewa commented on survey/support.md
> +Email: [dto.btn@tbs-sct.gc.ca](mailto:dto.btn@tbs-sct.gc.ca)
```suggestion
```

2023-04-04 14:31 UTC, LanaStewa commented on survey/support.md
> +* [When to contact the Digital Transformation Office](#when-to-contact-the-Digital-Transformation-Office)
```suggestion
* [When to contact the Digital Transformation Office](#when-to-contact-the-Digital-Transformation-Office)
* [When to contact Principal Publisher](#when-to-contact-Principal-Publisher)
```

2023-04-04 14:55 UTC, LanaStewa commented on survey/support.md
> +[Submit a Service Desk request (internal only)](http://requestform.portal.gc.ca/tickets.html)
```suggestion

```

2023-04-04 14:56 UTC, LanaStewa commented on survey/support.md
> +Submit a Service Desk request using the following categories from the drop-down menus:
```suggestion
[Submit a Service Desk request (internal only)](http://requestform.portal.gc.ca/tickets.html)

Submit a Service Desk request using the following categories from the drop-down menus:
```

2023-04-04 17:32 UTC, LanaStewa commented on survey/support.md
> +Submit a Service Desk request using the following categories from the drop-down menus:
```suggestion
[Submit a Service Desk request (internal only)](http://requestform.portal.gc.ca/tickets.html) using the following categories from the drop-down menus:
```

2023-04-05 21:04 UTC, delisma requested changes
Some E/F inconsistencies to address before the final merge

2023-04-05 21:04 UTC, delisma commented on survey/about-tss.md
> +
Missing content compared to the French alternative:

> Types de tâches&nbsp;:

Should we add it in English or remove it in French?

2023-04-05 21:04 UTC, delisma commented on survey/writing-tasks.md
> +        <p> Sign up for the [program]</p>
Missing content in French

2023-04-05 21:04 UTC, delisma commented on survey/writing-tasks.md
> +        <p> Enrol in the [program]</p>
Missing content in French

2023-04-05 21:04 UTC, delisma commented on survey/support.md
> +
Missing content compare to the English alternative:
> * rejoindre le groupe de travail

Should we add it in English or remove it in French?

2023-04-06 12:22 UTC, LanaStewa commented on survey/about-tss.md
> +
Add it in English
```suggestion
Types of tasks:
```

2023-04-06 12:27 UTC, LanaStewa commented on survey/writing-tasks.md
> +        <p> Sign up for the [program]</p>
It's not included in French because it's only relevant in English.  There's no equivalent issue.

2023-04-06 12:27 UTC, LanaStewa commented on survey/support.md
> +
It's not included in French because it's only relevant in English. There's no equivalent issue.

2023-04-06 16:35 UTC, delisma commented on survey/writing-tasks.md
> +        <p> Sign up for the [program]</p>
I'll open an issue for this one. I get what you mean but I feel that we should have an equivalent issue in French to avoid any OLA complaints. Something like "_S'inscrire_" vs "_S"enregistrer_" or something specific to the French language.

2023-04-06 16:43 UTC, delisma approved these changes
LGTM

2023-04-06 19:10 UTC, delisma approved these changes

2023-04-06 19:14 UTC, merged