migration: Content and Information Architecture Specification
canada-ca/design-system pull request #200
Opened 2023-03-13 12:11 UTC by prycrane

Pull request for moving Content and Information Architecture Specification section from AEM to design-system.

2023-03-28 13:24 UTC, delisma requested changes

2023-03-28 13:24 UTC, delisma commented on architecture/canada-content-information-architecture-specification.md
> +layout: default
Not necessary since they are declared in the _config.yml already

2023-03-28 13:24 UTC, delisma commented on architecture/canada-content-information-architecture-specification.md
> +- https://use.fontawesome.com/releases/v5.15.4/css/all.css
Not necessary since they are declared in the _config.yml already

2023-03-28 13:24 UTC, delisma commented on architecture/mandatory-elements.md
> +- https://use.fontawesome.com/releases/v5.15.4/css/all.css
Not necessary since they are declared in the _config.yml already

2023-03-28 13:24 UTC, delisma commented on architecture/mandatory-elements.md
> +layout: default
Not necessary since they are declared in the _config.yml already

2023-03-28 13:24 UTC, delisma commented on architecture/organizing-content.md
> +- https://use.fontawesome.com/releases/v5.15.4/css/all.css
Not necessary since they are declared in the _config.yml already

2023-03-28 13:24 UTC, delisma commented on architecture/organizing-content.md
> +layout: default
Not necessary since they are declared in the _config.yml already

2023-03-28 13:24 UTC, delisma commented on architecture/templates.md
> +- https://use.fontawesome.com/releases/v5.15.4/css/all.css
Not necessary since they are declared in the _config.yml already

2023-03-28 13:24 UTC, delisma commented on architecture/templates.md
> +layout: default
Not necessary since they are declared in the _config.yml already

2023-03-28 13:24 UTC, delisma commented on architecture/usage-canadaca-design.md
> +- https://use.fontawesome.com/releases/v5.15.4/css/all.css
Not necessary since they are declared in the _config.yml already

2023-03-28 13:24 UTC, delisma commented on architecture/usage-canadaca-design.md
> +layout: default
Not necessary since they are declared in the _config.yml already

2023-03-28 13:25 UTC, delisma commented
> Pull request for moving Content and Information Architecture Specification section from AEM to design-system.

Can you add the Pull Request in the Alternate language repo in the first comment above?

2023-04-03 17:30 UTC, delisma commented on ajax/patterns-01-en.json
> +    "NAME": "<a href=\"https://design.canada.ca/architecture/usage-canadaca-design.html\">Who has to use this design system</a>",
```suggestion
    "NAME": "<a href=\"{{ site.url }}/architecture/usage-canadaca-design.html\">Who has to use this design system</a>",

```
Using a variable in the URL allow us to test if the table works locally, in the staging area and in production, without us having to change the urls manually.

2023-04-03 17:31 UTC, delisma commented on ajax/patterns-01-en.json
> +    "NAME": "<a href=\"https://design.canada.ca/architecture/mandatory-elements.html\">Mandatory elements</a>",
```suggestion
    "NAME": "<a href=\"{{ site.url }}/architecture/mandatory-elements.html\">Mandatory elements</a>",

```

2023-04-03 17:31 UTC, delisma commented on ajax/patterns-01-en.json
> +    "NAME": "<a href=\"https://design.canada.ca/architecture/organizing-content.html#toc1\">User navigation</a>",
```suggestion
    "NAME": "<a href=\"{{ site.url }}/architecture/organizing-content.html#toc1\">User navigation</a>",

```

2023-04-03 17:31 UTC, delisma commented on ajax/patterns-01-en.json
> +    "NAME": "<a href=\"https://design.canada.ca/architecture/organizing-content.html#user\">User-need categories for destination content</a>",
```suggestion
    "NAME": "<a href=\"{{ site.url }}/architecture/organizing-content.html#user\">User-need categories for destination content</a>",

```

2023-04-03 17:32 UTC, delisma commented on ajax/patterns-01-en.json
> +    "NAME": "<a href=\"https://design.canada.ca/architecture/organizing-content.html#toc3\">URL model</a>",
```suggestion
    "NAME": "<a href=\"{{ site.url }}/architecture/organizing-content.html#toc3\">URL model</a>",

```

2023-04-03 17:33 UTC, delisma commented on ajax/patterns-01-en.json
> +    "NAME": "<a href=\"https://design.canada.ca/architecture/templates.html#principles\">Design principles</a>",
```suggestion
    "NAME": "<a href=\"{{ site.url }}/architecture/templates.html#principles\">Design principles</a>",

```

2023-04-04 13:42 UTC, prycrane commented on ajax/patterns-01-en.json
> +    "NAME": "<a href=\"https://design.canada.ca/architecture/usage-canadaca-design.html\">Who has to use this design system</a>",
I have updated the urls.

2023-04-04 13:44 UTC, prycrane commented
Do you want to meet this afternoon and maybe flip this into production?

2023-04-17 12:51 UTC, delisma approved these changes

2023-05-03 18:06 UTC, delisma requested changes

2023-05-03 18:06 UTC, delisma commented on architecture/canada-content-information-architecture-specification.md
> +<p class="gc-byline"><strong>From: <a href="/en/treasury-board-secretariat.html">Treasury Board of Canada Secretariat</a></strong></p>
```suggestion
<p class="gc-byline"><strong>From: <a href="hhtps://www.canada.ca/en/treasury-board-secretariat.html">Treasury Board of Canada Secretariat</a></strong></p>
```

2023-05-03 18:06 UTC, delisma commented on mandatory-templates/theme-pages-backup.html
Should be deleted. Will file issue in the future

2023-05-03 18:06 UTC, delisma commented on mandatory-templates/theme-topic-draft.html
Should be deleted. Will file issue in the future

2023-05-03 18:06 UTC, delisma commented on architecture/organizing-content.md
> +      <img src="https://www.canada.ca/content/dam/tbs-sct/images/government-communications/canada-content-style-guide/conceptual-overview-eng.png" class="img-responsive center-block" alt="Diagram of
```suggestion
      <img src="https://www.canada.ca/content/dam/tbs-sct/images/government-communications/canada-content-style-guide/conceptual-overview-eng.png" class="img-responsive center-block" alt="Diagram of user navigation conceptual overview. Text version below:">
```
Change the dam thing

2023-05-03 18:06 UTC, delisma commented on architecture/organizing-content.md
> +<p class="gc-byline"><strong>From: <a href="/en/treasury-board-secretariat.html">Treasury Board of Canada Secretariat</a></strong></p>
```suggestion
<p class="gc-byline"><strong>From: <a href="/en/treasury-board-secretariat.html">Treasury Board of Canada Secretariat</a></strong></p>
```
Absolute URL to use

2023-05-04 12:24 UTC, prycrane commented on architecture/canada-content-information-architecture-specification.md
> +<p class="gc-byline"><strong>From: <a href="/en/treasury-board-secretariat.html">Treasury Board of Canada Secretariat</a></strong></p>
Done

2023-05-04 12:27 UTC, prycrane commented on architecture/organizing-content.md
> +      <img src="https://www.canada.ca/content/dam/tbs-sct/images/government-communications/canada-content-style-guide/conceptual-overview-eng.png" class="img-responsive center-block" alt="Diagram of
done

2023-05-04 12:27 UTC, prycrane commented on architecture/organizing-content.md
> +<p class="gc-byline"><strong>From: <a href="/en/treasury-board-secretariat.html">Treasury Board of Canada Secretariat</a></strong></p>
Done

2023-05-08 17:42 UTC, delisma approved these changes
LGTM

2023-05-17 19:41 UTC, delisma approved these changes
LGTM

2023-05-17 20:02 UTC, merged