fix: site-footer-edits
canada-ca/design-system pull request #222
Opened 2023-04-06 11:23 UTC by prycrane

2023-04-06 17:14 UTC, delisma requested changes
We need to remove the Page Feedback Widget from these pages otherwise it will conflicts with the default layout.

2023-04-06 17:14 UTC, delisma commented on common-design-patterns/site-footer-contextual.md
> +<!-- START PAGE FEEDBACK WIDGET -->
We should remove the feedback widget

2023-04-06 17:14 UTC, delisma commented on common-design-patterns/site-footer-main.md
> +  <div class="mwsgeneric-base-html parbase section">
These classes are AEM specific.

2023-04-06 17:14 UTC, delisma commented on common-design-patterns/site-footer-main.md
> +<!-- START PAGE FEEDBACK WIDGET -->
With the default layout we have to remove the Page Feedback Widget.

2023-04-06 17:14 UTC, delisma commented on common-design-patterns/site-footer-sub.md
> +  <div class="mwsgeneric-base-html parbase section">
These classes are specific to AEM

2023-04-06 17:14 UTC, delisma commented on common-design-patterns/site-footer-sub.md
> +<!-- START PAGE FEEDBACK WIDGET -->
We should remove the Page Feedback Widget

2023-04-06 17:14 UTC, delisma commented on common-design-patterns/site-footer.md
> +<!-- START PAGE FEEDBACK WIDGET -->
We should remove the Page Feedback Widget

2023-04-06 17:46 UTC, prycrane commented on common-design-patterns/site-footer-contextual.md
> +<!-- START PAGE FEEDBACK WIDGET -->
Done.

2023-04-06 17:49 UTC, prycrane commented on common-design-patterns/site-footer-main.md
> +  <div class="mwsgeneric-base-html parbase section">
Fixed.

2023-04-06 17:49 UTC, prycrane commented on common-design-patterns/site-footer-main.md
> +<!-- START PAGE FEEDBACK WIDGET -->
Done

2023-04-06 17:50 UTC, prycrane commented on common-design-patterns/site-footer-sub.md
> +  <div class="mwsgeneric-base-html parbase section">
Fixed

2023-04-06 17:50 UTC, prycrane commented on common-design-patterns/site-footer-sub.md
> +<!-- START PAGE FEEDBACK WIDGET -->
Done

2023-04-06 17:50 UTC, prycrane commented on common-design-patterns/site-footer.md
> +<!-- START PAGE FEEDBACK WIDGET -->
Done

2023-04-11 17:54 UTC, LPipes4 commented on common-design-patterns/site-footer.md
Something happened with the preview of this one - only the code shows. Need to double check what's going on before we push it. The first 2 pages look fine and are ready to go. For this one, maybe it's just the preview that's broken but we need to have a look and see.

2023-04-11 17:57 UTC, LPipes4 requested changes

2023-04-11 17:57 UTC, LPipes4 commented on common-design-patterns/site-footer.md
> +---
I tried putting this at the top of the preview, but got an error saying I had to leave a comment, so adding it here to...Something happened with the preview of this one - only the code shows. Need to double check what's going on before we push it. The first 2 pages look fine and are ready to go. For this one, maybe it's just the preview that's broken but we need to have a look and see.

2023-04-17 11:31 UTC, prycrane commented on common-design-patterns/site-footer.md
> +---
Fixed

2023-04-17 11:31 UTC, prycrane commented on common-design-patterns/site-footer.md
Fixed.

2023-04-18 14:59 UTC, LPipes4 approved these changes

2023-06-08 11:31 UTC, prycrane commented
@delisma - please confirm that the <h1> will present properly once published.  It's an older pull request that was waiting for https://github.com/canada-ca/systeme-conception/pull/128 to be merged (now merged).  Give it a final check (I removed all the feedback references) and we should be good to go.  @LPipes4 is reviewing the French pull request (https://github.com/canada-ca/systeme-conception/pull/131). Thanks.

2023-06-20 17:27 UTC, delisma approved these changes
LGTM

2023-06-26 11:12 UTC, closed without merging