fix issue 249
canada-ca/design-system pull request #250
Opened 2023-05-19 19:34 UTC by jmealing

Fixing: https://github.com/canada-ca/design-system/issues/249

FR (coming soon)

2023-05-23 18:51 UTC, delisma requested changes

2023-05-23 18:51 UTC, delisma commented on architecture/mandatory-elements.md
Should we apply this patch to the French equivalent as well?

2023-05-23 19:12 UTC, jmealing commented on architecture/mandatory-elements.md
I see the page navigation on the bottom is here already. Only the FR was missing it. The EN just needed links updated.

2023-05-23 21:22 UTC, delisma approved these changes
Pre-approved. Waiting for the alternate language PR to be approved too.

2023-06-02 18:12 UTC, prycrane commented
I fixed the alignment on canada-content-information-architecture-specification.html

2023-06-07 12:45 UTC, merged