PFT - latest changes/datatable update
canada-ca/design-system pull request #348
Opened 2023-10-13 13:21 UTC by prycrane

2023-11-07 14:21 UTC, donohuech commented on about/latest-changes.md
> +dateModified: 2023-10-20
Please change to 2023-11-07

2023-11-07 14:23 UTC, donohuech commented on about/latest-changes.md
> +    <summary>October  20, 2023</summary>
Please change to November 7, 2023

2023-11-07 14:23 UTC, donohuech requested changes
A few date changes please @prycrane

2023-11-07 14:41 UTC, prycrane commented on about/latest-changes.md
> +dateModified: 2023-10-20
Done

2023-11-07 14:41 UTC, prycrane commented on about/latest-changes.md
> +    <summary>October  20, 2023</summary>
Done

2023-11-08 15:15 UTC, donohuech approved these changes

2023-11-08 16:09 UTC, merged