Remove TB references
canada-ca/design-system pull request #354
Opened 2023-10-25 11:31 UTC by prycrane

Remove Treasury Board references from DTO material.

**Preview**

**French PR**

2023-10-25 12:38 UTC, prycrane commented
@delisma - I removed the underscored files.  They are now out of date and i don't want to update ROTed files.  They are still available in the history.  Is that okay?

2023-10-25 15:46 UTC, delisma approved these changes
Pending French PR approval

2023-10-25 16:22 UTC, nschonni commented on architecture/mandatory-elements.md
> +---<div class="mrgn-tp-md mrgn-bttm-sm brdr-bttm">
This breaks the frontmatter, the DIV needs to be on its own line. This happened in a few files

2023-10-25 16:32 UTC, delisma commented on architecture/mandatory-elements.md
> +---<div class="mrgn-tp-md mrgn-bttm-sm brdr-bttm">
```suggestion
---
<div class="mrgn-tp-md mrgn-bttm-sm brdr-bttm">
```

2023-10-25 16:34 UTC, delisma requested changes

2023-10-25 16:34 UTC, delisma commented on architecture/organizing-content.md
> +---<div class="mrgn-tp-md mrgn-bttm-sm brdr-bttm">
```suggestion
---
<div class="mrgn-tp-md mrgn-bttm-sm brdr-bttm">
```

2023-10-30 11:08 UTC, prycrane commented on architecture/mandatory-elements.md
> +---<div class="mrgn-tp-md mrgn-bttm-sm brdr-bttm">
fixed

2023-10-30 13:58 UTC, donohuech approved these changes

2023-10-30 17:15 UTC, delisma approved these changes

2023-10-30 17:17 UTC, merged